service: nx-dcsoftware

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1 # EU (Frankfurt) Region

plugins:
  - serverless-finch

custom:
  client:
    bucketName: nx-dcsoftware # Change this to a universally unique bucket name
    distributionFolder: ../../dist/dcsoftware
