name: CodeQL

on:
  pull_request:
    branches: master

  schedule:
    - cron: "41 1 * * 2"

jobs:
  analyze:
    name: Analyze

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ "javascript", "typescript" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
