name: Deploy dcsoftware

on:
  push:
    branches:
      - master
    paths:
      - 'apps/www.dcsoftware.io/**'
  pull_request:
    branches:
     - master

jobs:
    deploy_2:

      name: Deploy www.dcsoftware.io
      runs-on: ubuntu-latest

      permissions:
        id-token: write # Needed for auth with Deno Deploy
        contents: read # Needed to clone the repository

      steps:
        - name: Clone repository
          uses: actions/checkout@v4

        - name: Install Deno
          uses: denoland/setup-deno@v2
          with:
            deno-version: v2.x

        - name: Install Node.js
          uses: actions/setup-node@v4
          with:
            node-version: lts/*

        - name: Install step
          run: |
            npm ci

        - name: Build step
          run: |
            cd apps/www.dcsoftware.io
            npm run build

        - name: Upload to Deno Deploy
          uses: denoland/deployctl@v1
          with:
            project: "dcsoftware"
            entrypoint: "https://deno.land/std@0.217.0/http/file_server.ts"
            root: "apps/www.dcsoftware.io/dist"

