# This is a basic workflow to help you get started with Actions

name: PR Checks

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  lint_and_test_changed:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint:changed

      - name: Test
        run: yarn test:changed

      # This workflow contains a single job called "build"
  build_changed:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install
        run: yarn install --frozen-lockfile

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          yarn lerna run build --since origin/master
